server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
api:
  security:
    token:
      secret_key: ${JWT_SECRET:secret_key}
      issuer: ${springapp:springapp}